### ISSUE TITLE
Denied mission is still processed

### ISSUE THREAD

**Issue by BartKieviet** [Tsunder/Pardus-Sweetener#45]
situation
When taking a mission that is not acceptable (_e.g._, because not enough cargo space).

expected behavior
Mission is not added.

actual behavior
the mission is still added to the list.

thoughts
The problem here lies in that the message frame gives the UI error, and not in the missions page. Perhaps link the mission processing to the onChange event instead of the onClick event?

**Comment by Tsunder** [comment]
Related (and perhaps best addressed at the same time):
Missions that are no longer available (often times from the pilot double clicking, and now a days less frequently mission jacking, or mission board refreshing) to also be added (double clicking = 2 tracked missions!).

in this case, the job board shows "not offered" for the relevant job, and an error message in msg frame is displayed.

expected behaviour of course is for the mission to not be added.

**Comment by BartKieviet** [comment]
fixed in 02bdacfd5cc77aae48e9d81870fdaa190379b48a
